### ISSUE TITLE
AWS documentation

### ISSUE THREAD

**Issue by gshiva** [carlossg/kubernetes-jenkins#3]
I see documentation/scripts for GKE. Is it possible to add something similar for AWS?

Thanks

**Comment by adaughterson** [comment]
Me too: I'm trying to apply the examples to an AWS backend, and running into issues which I'm not finding relevant answers for.

**Comment by carlossg** [comment]
What do you mean by AWS ? a Kubernetes cluster running on EC2 ?

**Comment by adaughterson** [comment]
Thanks for responding so quickly. Sorry, my "Me too" was pretty vague.
Yes I do mean a Kubernetes cluster with a Jenkins master (leader now?) service/pod, Jenkins slave (agent now?) service/pod all running in AWS et al.
I've been attempting to use kube-up.sh and kube-aws, but your examples are nice and succinct, only lacking yaml and json for EC2 (unless they are interchangeable, and I simply need to use the AWS terms).
